apiVersion: apps/v1
kind: Deployment
metadata:
  name: articles-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: articles-service
  template:
    metadata:
      labels:
        app: articles-service
    spec:
      containers:
        - name: moleculer-app
          image: YOUR_DOCKERHUB_USERNAME/moleculer-conduit:latest
          imagePullPolicy: Always
          env:
            - name: SERVICES
              value: "services/articles.service.js"
            - name: TRANSPORTER
              value: "nats://nats-service:4222"
            - name: MONGO_URI
              value: "mongodb://REPLACE_WITH_DB_PRIVATE_IP:27017/conduit"