apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: comments-service
  template:
    metadata:
      labels:
        app: comments-service
    spec:
      containers:
        - name: moleculer-app
          image: YOUR_DOCKERHUB_USERNAME/moleculer-conduit:latest
          imagePullPolicy: Always
          env:
            - name: SERVICES
              value: "services/comments.service.js"
          envFrom:
            - configMapRef:
                name: moleculer-env