apiVersion: v1
kind: ConfigMap
metadata:
  name: moleculer-env
data:
  # KEEP: NATS is inside Kubernetes, so we use the internal DNS name
  TRANSPORTER: "nats://nats-service:4222"

  # CHANGE: Point to the AWS DB Instance IP
  MONGO_URI: "mongodb://10.0.3.215:27017/conduit"

  NODE_ENV: "production"
  NAMESPACE: "realworld"