apiVersion: apps/v1
kind: Deployment
metadata:
  name: follows-service
spec:
  replicas: 2 # You can scale this because you have 6 worker nodes!
  selector:
    matchLabels:
      app: follows-service
  template:
    metadata:
      labels:
        app: follows-service
    spec:
      containers:
      - name: moleculer-app
        image: moleculer-registry:5000/moleculer-conduit:local
        imagePullPolicy: Always
        env:
        - name: SERVICES
          value: "services/follows.service.js"         # Only starts the Users service
        - name: TRANSPORTER
          value: "nats://nats-service:4222"
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017/conduit"